/** @type {import('tailwindcss').Config} */
module.exports = {
  purge: ['./src/**/*.html', './src/**/*.php'],
  content: [
    './**/*.php',
    './assets/js/**/*.js',
    './assets/css/**/*.css',
    './theme.json',
    './templates/**/*.php',
    './patterns/**/*.php',
    './blocks/**/*.js',
    './theme/**/*.php',
    './theme/**/*.twig',
    './theme/**/*.html',
    './wp-content/themes/actonaid/**/*.php',
    './wp-content/uploads/**/*.html',
  ],
  safelist: [
    'absolute',
    'bg-black/70',
    'bg-gradient-to-b',
    'bg-zinc-200',
    'block',
    'cursor-pointer',
    'duration-700',
    'fixed',
    'flex',
    'from-black/70',
    'group',
    'group-open:-rotate-45',
    'group-open:-top-2',
    'group-open:opacity-0',
    'group-open:rotate-45',
    'group-open:top-2',
    'h-1',
    'h-14',
    'left-0',
    'left-6',
    'mb-2',
    'md:hidden',
    'md:w-[20%]',
    'md:w-[70%]',
    'ml-auto',
    'mt-1',
    'mx-auto',
    'my-auto',
    'opacity-0',
    'opacity-100',
    'p-4',
    'pb-4',
    'peer',
    'peer-open:opacity-100',
    'px-4',
    'py-16',
    'relative',
    'right-8',
    'rounded-b-lg',
    'rounded-full',
    'text-center',
    'to-red/90',
    'top-0',
    'top-1/2',
    'top-14',
    'top-[56px]',
    'transition-all',
    'transition-opacity',
    'w-10',
    'w-8',
    'w-[30%]',
    'w-[90%]',
    'w-full',
    'xl:w-auto',
    'z-10',
    'z-20',
  ],
  theme: {
    extend: {
      colors: {
        black: '#000',
        white: '#fff',
        red: '#cd0c0c',
        purpleG: '#7B6D8D',
        greenG: '#619B8A',
      },
      fontFamily: {
        bitter: ['Bitter', 'serif'],
        zilla: ['Zilla Slab', 'serif'],
      },
    },
  },
  plugins: [
    require('./plugins/openVariant'),
    require('./plugins/linearGradient'),
    require('./plugins/btnAnimate'),
  ],
};
